version: "3"

services:
  web:
    build:
      context: ../../
    ports:
      - 8000:8000
    env_file:
      - web.env
    command: bash -c "python manage.py wait_for_db &&
                      python manage.py makemigrations &&
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  db:
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data/
    env_file:
      - db.env

volumes:
  db_volume:
