version: "3"

services:

  backend:
    build:
      context: ../../backend
      args:
        "USER_ID": $USER_ID
        "GROUP_ID": $GROUP_ID
    container_name: ${PROJECT_PREFIX}_backend
    ports:
      - 8000:8000
    volumes:
      - ../../backend:/backend
    depends_on:
      - db
    command: bash -c "python manage.py wait_for_db &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"


  db:
    image: postgres:11
    container_name: ${PROJECT_PREFIX}_db
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust


  frontend:
    build:
      context: ../../frontend
    container_name: ${PROJECT_PREFIX}_frontend
    ports:
      - 3000:3000
    volumes:
      - ../../frontend/public:/frontend/public
      - ../../frontend/src:/frontend/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    depends_on:
      - backend
    command: bash -c "npm start"


volumes:
  db_volume:
